apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      labels:
        app: homework
    spec:
      containers:
      - name: homework
        image: ghcr.io/lukacsi/homework:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: homework-service
spec:
  type: NodePort
  selector:
    app: homework
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080

